name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on:
      - self-hosted
      - deployment
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          clean: false

      - name: Set Release Version
        run: |
            echo "BUILD_VERSION=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      #- name: Configure .env
       # run: |
        #  echo "DOMAIN_NAME=${{ vars.DOMAIN_NAME }}" >> .env
         # echo "TLS_EMAIL=${{ secrets.TLS_EMAIL }}" >> .env
          #echo "LDAP_SERVER_IP=${{ vars.LDAP_SERVER_IP }}" >> .env
          #echo "RSA_PRIVATE_KEY_FILE=private.pem" >> .env
          #echo "RSA_PUBLIC_KEY_FILE=public.pem" >> .env

     #   working-directory: ./deployment
     # - name: Download Plugins
     #   run: bash ./builder.sh
     #   working-directory: ./deployment

      - name: Build
        run: docker compose build --pull
        working-directory: ./deployment

#      - name: Add keys
 #       if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
  #      run: |
   #       echo "${{ secrets.RSA_PRIVATE_KEY }}" > ./deployment/private-keys/private.pem
     #     echo "${{ secrets.RSA_PUBLIC_KEY }}" > ./deployment/private-keys/public.pem
    #      echo "${{ secrets.RSA_PUBLIC_KEY }}" > ./deployment/public-keys/public.pem

      #- name: Deploy
       # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        #run:  |
         # docker compose up -d
          #docker compose restart
        #working-directory: ./deployment

      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Github Container registry
        run: docker push ghcr.io/anuraj/minimalapi:${{ env.BUILD_VERSION }}
