name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  publish:
    name: Publish on GHCR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          clean: false

      - name: Set Release Version
        run: echo "TAG=$(git show -s --format=%cd --date=format:%Y-%m-%d_%H-%M-%S ${{ github.sha }})" >> ${GITHUB_ENV}

      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: docker compose build
        working-directory: ./deployment

      - name: Push
        run: docker compose push
        working-directory: ./deployment

      - name: Update latest
        run: docker compose build && docker compose push
        working-directory: ./deployment
        env:
          TAG: latest
